Update zabbix_action.py fix ep8 issue(s)
Found 1 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/zabbix_action.py:812:1: E302: expected 2 blank lines, found 1