Zabbix actions discovery checks with condtions (#1473)
* Zabbix actions discovery checks with condtions

* Update zabbix_action.py

Fix after sanity test

* Update zabbix_action.py fix ep8 issue(s)

Found 1 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/zabbix_action.py:812:1: E302: expected 2 blank lines, found 1

* Update changelogs/fragments/zabbix_action_dcheck.yml

Co-authored-by: Evgeny Yurchenko <ey@bgmot.com>

---------

Co-authored-by: Анисимов Николай Георгиевич <n.anisimov@n3med.ru>
Co-authored-by: Evgeny Yurchenko <ey@bgmot.com>